### ISSUE TITLE
Icons unrecognisable in the statusbar

### ISSUE THREAD

**Issue by andrewshadura** [vimperator/vimperator-labs#15]
Some icons when placed into the statusbar become distorted and unreadable: RSS, Adblock Plus, Downloads and others.

![2014-07-24-111108_889x34_scrot](https://cloud.githubusercontent.com/assets/309253/3686001/8793d61c-1312-11e4-9844-7c1a7bd9c190.png)

**Comment by omeid** [comment]
Still looking for a fix for this.

**Comment by timss** [comment]
I played around with this a little bit, and it might seem that addons without icons at 24 px breaks, or if the addon doesn't use 24 px for its svg files. Can anyone confirm? 

For example Self Destructing Cookies have an icon at 24 px, while µBlock does not and NoScript does not. 

![addon icons](http://i.imgur.com/4etnlv7.png)

Tried to resize the icon in use by µBlock to 24x24, but didn't seem to help. I could have done something wrong though, or overseen some hardcoded 19 px in its source code. Here it is if anyone want to test:

https://github.com/gorhill/uBlock/blob/master/src/img/browsericons/icon19-off.png

Information regarding addon icon sizes:

https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Toolbars/Creating_toolbar_buttons#Icon_size

While a workaround could probably be made in Vimperator, it seems to me that the origin of this bug is poorly behaving addons, or have I misunderstood something?

**Comment by timss** [comment]
The new version 0.4.7 of Self-Destructing cookies breaks with a large icon.

Diff can be found here if anyone feels like digging further:
\- https://addons.mozilla.org/en-US/firefox/files/compare/277030...297496/

**Comment by omeid** [comment]
```css
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

#liberator-bottombar toolbarbutton {
min-height: 32px;
     padding:0;
     margin:0;
}
```

This user script makes the statusline as it shows in "customize" mode.

**Comment by omeid** [comment]
After struggling a lot to try and make the vimperator statusline sane, I give up and moved to [pentadactyl](http://5digits.org/pentadactyl).

**Comment by Stebalien** [comment]
The following css fixes it:
```css
#liberator-bottombar toolbarbutton {
    -moz-appearance: none;
    margin: 0px 2px;
}
```

**Comment by guyhughes** [comment]
@Stebalien You got more tipps? I'm getting this :sob: 
![2015-12-10-223849_540x45_scrot](https://cloud.githubusercontent.com/assets/5915486/11735446/5632a35e-9f8f-11e5-87e1-c4b7cfa6ed83.png)
![2015-12-10-224353_553x42_scrot](https://cloud.githubusercontent.com/assets/5915486/11735463/8428aefc-9f8f-11e5-9ab6-6c335957661f.png)

Trying this
```css
#liberator-bottombar toolbarbutton, #liberator-statusline toolbarbutton {
    -moz-appearance: none;
    margin: 0px 2px;
}
```

**Comment by Stebalien** [comment]
For me, it works with noscript, ublock, and self-destructing cookies. I don't know what could be goingwrong in your case. Sorry.

**Comment by maturano** [comment]
I'm getting this:
![2015-12-16-113735_648x45_scrot](https://cloud.githubusercontent.com/assets/5768813/11848727/9ee33330-a3e9-11e5-928e-5d87d5ddc05b.png)


With this code:

```css
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

#liberator-bottombar toolbarbutton {
    min-height: 24px;
    padding: 0;
    margin: 0;
}
```

**Comment by c6parmak** [comment]
While using DOM Inspector, I found that `toolbarbutton`s has strange border-widths, I tried setting them to 0px without any success.
![2016-04-04-140545_287x101_scrot](https://cloud.githubusercontent.com/assets/80478/14248824/42366c32-fa7f-11e5-9d6a-7141cd2dc23c.png)

Giving negative margins to icons in toolbarbuttons seems to solve squeezing for me on Firefox 44, margin-right is ignored though.
```css
#liberator-statusline toolbarbutton .toolbarbutton-icon {
  margin-top: -6px;
  margin-right: -9px;
  margin-bottom: -7px;
  margin-left: -9px;
}
```
Let's put everything on statusline, yay! (statusline height is16px)
![2016-04-04-160637_476x20_scrot](https://cloud.githubusercontent.com/assets/80478/14248825/4236ea90-fa7f-11e5-92d8-45ccb36534ef.png)
