### ISSUE TITLE
Search/clear icon in command line

### ISSUE THREAD

**Issue by SammysHP** [vimperator/vimperator-labs#268]
The last update of vimperator added search/clear icons to the command line. IMHO they are unnecessary and ugly.

I assume that it is caused by c2a5972fbf16b597dd0580559e921d029c62fd53.

As a workaround I added the following line to my userChrome.css:

```css
#liberator-commandline-command .textbox-search-icons {display: none !important;}
```
